# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: ubuntu:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - .apt/
    - venv/

before_script:
    # Configure apt chaching
  - echo $CI_PROJECT_DIR
  - export APT_DIR=$CI_PROJECT_DIR/.apt && export APT_STATE_LISTS=$APT_DIR/lists && export APT_CACHE_ARCHIVES=$APT_DIR/archives
  - printf "dir::state::lists    ${APT_STATE_LISTS};\ndir::cache::archives    ${APT_CACHE_ARCHIVES};\n" > /etc/apt/apt.conf
  - mkdir -p "${APT_STATE_LISTS}/partial" && mkdir -p "${APT_CACHE_ARCHIVES}/partial"
  - apt-get update -y && apt-get install -y python3
  - apt-get install curl -y
  - python3 -V  # Print out python version for debugging
  - apt-get install default-jdk -y
  - apt-get install python3-pip -y
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install spacy
  - pip3 install pandas
  - pip3 install tika

test:
  script:
    - python3 parser.py test
    - echo "thi"